# Name of the Namespace to use
namespace: mongodb

## Operator
operator:
  # Name that will be assigned to most of internal Kubernetes objects like Deployment, ServiceAccount, Role etc.
  name: mongodb-kubernetes-operator

  # Name of the operator image
  operatorImageName: mongodb-kubernetes-operator

  # Name of the deployment of the operator pod
  deploymentName: mongodb-kubernetes-operator

  # Version of mongodb-kubernetes-operator
  version: 0.7.0

## Operator's database
database:
  name: mongodb-database

agent:
  name: mongodb-agent
  version: 11.0.5.6963-1
versionUpgradeHook:
  name: mongodb-kubernetes-operator-version-upgrade-post-start-hook
  version: 1.0.2
readinessProbe:
  name: mongodb-kubernetes-readinessprobe
  version: 1.0.4
mongodb:
  name: mongo
  repo: docker.io

registry:
  agent: quay.io/mongodb
  versionUpgradeHook: quay.io/mongodb
  readinessProbe: quay.io/mongodb
  operator: quay.io/mongodb
  pullPolicy: Always

createResource: false
resource:
  name: mongodb-replica-set
  version: 4.4.0
  members: 3
  tls:
    enabled: false
    useCertManager: false
    certificateKeySecretRef: tls-certificate
    caCertificateSecretRef: tls-ca-key-pair
