blank_issues_enabled: false
contact_links:
    - name: MongoDB Feedback
      url: https://feedback.mongodb.com/forums/924355-ops-tools
      about: Use our Feedback page for making feature requests.
