apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ./crds/mongodb.com_mongodb_crd.yaml
 - ./operator/service_account.yaml
 - ./operator/role.yaml
 - ./operator/role_binding.yaml
 - ./operator/operator.yaml

