apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e-test
  # namespace is 'default' for the e2e tests because the TLS certificates 
  # generated used as test fixture (in the TLS tests) only work with the 
  # default namespace.
  namespace: default
