apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef:
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram

  statefulSet:
    serviceName: example-openshift-mongodb-svc
    selector: {}
    template:
      spec:
        volumes:
          - name: custom-volume
            emptyDir: {}
        containers:
        - name: mongodb-agent
          volumeMounts:
            - name: custom-volume
              mountPath: /my-custom-version/mount-path
