name: Kubelinter-check

on:
  push:
    branches:
    - master
    paths-ignore: 
    - docs/**
  pull_request:
    branches:
    - master
    paths-ignore:
    - docs/**
  workflow_dispatch: {}

jobs:
  Kubelinter-check:
    name: Run Kube-linter check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Scan directory ./deploy/clusterwide/ with kube-linter
      uses: stackrox/kube-linter-action@v1
      with:
        directory: deploy/clusterwide
        config: ${GITHUB_WORKSPACE}/.github/config_files/config_lint.yaml

    - name: Scan directory ./deploy/openshift/ with kube-linter
      uses: stackrox/kube-linter-action@v1
      with:
        directory: deploy/openshift
        config: ${GITHUB_WORKSPACE}/.github/config_files/config_lint_openshift.yaml

    - name: Scan directory ./config/manager/ with kube-linter
      uses: stackrox/kube-linter-action@v1
      with:
        directory: config/manager/manager.yaml
        config: ${GITHUB_WORKSPACE}/.github/config_files/config_lint.yaml

    - name: Scan directory ./config/samples/ with kube-linter
      uses: stackrox/kube-linter-action@v1
      with:
        directory: config/samples
        config: ${GITHUB_WORKSPACE}/.github/config_files/config_lint.yaml
